Lab Day 2: Experiments 4 to 8 of GroupB syllabus
* 4. Create, concatenate, and print a string and access a sub-string from a given string
* 5. Familiarize time and date in various formats
* 6. Write a program to create, append, and remove lists in Python using numpy
* 7. Program to find the largest of three numbers
* 8. Convert temperatures to and from Celsius and Fahrenheit.

# String Concatenation, slicing

In [16]:
'''Following code is an adapted version of stringdemo.py in the home directory by Prof. Sarju S.'''
# Define the first and last names
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

Enter your first name: Jacob
Enter your last name: Mathew


In [31]:
# Concatenate the first and last name with a space
full_name = first_name + " " + last_name

# Print the concatenated string
print("Concatenated string: ", full_name)

Concatenated string:  Jacob Mathew


In [20]:
#If in need to print the first 3 letters; ie index 0,1,2
beginning=full_name[:3]
print(beginning)

Jac


In [22]:
#print next 2 letters; ie index 3,4
print(full_name[3:5])

ob


In [23]:
#print rest of the name
print(full_name[5:])

 Mathew


In [24]:
#print every alternate alphabet
print(full_name[::2])

JcbMte


In [26]:
#print from index 3rd, 5th, 7th and 9th characters
print(full_name[2:10:2])

cbMt


In [32]:
# Access and print the sub-string (last name only)
length_of_first_name=len(first_name)
last_name_substring = full_name[length_of_first_name+ 1:]
print("Sub-string (last name): ", last_name_substring)

Sub-string (last name):  Mathew


In [2]:
full_name = input("Enter Full name:")

#Split the name at places where spaces occur
parts = full_name.split(" ")
print(parts)

Enter Full name:Jacob Mathew
['Jacob', 'Mathew']


In [3]:
#print the first split form the split that we did before
print(parts[0])

Jacob


In [6]:
#You can split a string using other characters also. Eg split using comma
cs_list=input("Enter a comma separated sequence of names:")
parts = cs_list.split(",")
print(type(parts))
print(len(parts))
print(parts)
#We have now inputted a list from user!!

Enter a comma separated sequence of names:asdf,jklm,opq
<class 'list'>
3
['asdf', 'jklm', 'opq']


In [3]:
#Ok.. so + does concatenation of two strings. What does * do?
name="ATP-"
out=name*5
print(out)

ATP-ATP-ATP-ATP-ATP-


In [7]:
#(Multiplication is repeated addition/concatenation). let's see what this gives
for i in range(10):
    print('-' * i)


-
--
---
----
-----
------
-------
--------
---------


In [12]:
#EXERCISE: Can you print an isosceles triangle of height n? Hint use ' '*(n-i) + '-'*(2i+1)

          -
         ---
        -----
       -------
      ---------
     -----------
    -------------
   ---------------
  -----------------
 -------------------


In [ ]:
#EXERCISE: Inverted pyramids anyone? Hint use range(n,0,-1)? Any other way?

# List concatenation, slicing

In [14]:
#Most of what you did for strings can be used for lists also
L1=[1,2,3]
L2=[4,5,6]
print(L1+L2) #Concatenation of lists
print(L1*3)  #Repeated self concatenation of lists; L1*3 = L1+L1+L1

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [27]:
#EXERCISE: Try slicing [start:stop:step] to print various sub parts of the list L=[0,1,2,3,4,5,6,7,8,9,10]
#eg: first to elements
L=[0,1,2,3,4,5,6,7,8,9,10]
print(L[:2])

[0, 1]


In [30]:
#Negative inices can also be given inside slice operation
print(L[-2])
print(L[-2:])

9
[9, 10]


# Date and Time
Following code is an adapted version of datetimedemo.py in the home directory by Prof. Sarju S.

Here we use the datetime module. Modules are another technique in python for modularity. A module is a set of related functions and datatypes that are functionally related to each other.
eg: datetime module provides a lot of functions to get current time, convert time between formats, and many other functions related to date and time managment in computers.
numpy module provides a lot of numerical method functions for scientific/engineering computations.

To use the functions in a module you have to import it first. There are several formats to import a module

import datetime

import datetime as dt

from datetime import datetime

Each line has import keyword. More on these various formats in lecture class, after we learn functions

In [71]:
from datetime import datetime

# Get the current date and time
current_time = datetime.now()

# Display the current date and time
print("Current date and time:", current_time)
print(type(current_time))

Current date and time: 2024-11-07 11:35:43.922184
<class 'datetime.datetime'>


In [73]:
# Display in the format [YYYY-MM-DD HH:MM:SS]
'''strftime() is a POSIX standard function, implemented across various operating systems, in various languages like C, python etc.
The formatting codes are hence standard across many languages. You can get more details about the formatting codes
using man strftime on any unix/linux terminal, or by searching in the internet'''

formatted_1 = current_time.strftime("%Y-%m-%d %H:%M:%S")
print("Format [YYYY-MM-DD HH:MM:SS]:", formatted_1)

Format [YYYY-MM-DD HH:MM:SS]: 2024-11-07 11:35:43


In [61]:
# Display in the format [MM/DD/YYYY]
formatted_2 = current_time.strftime("%m/%d/%Y")
print("Format [MM/DD/YYYY]:", formatted_2)

Format [MM/DD/YYYY]: 11/07/2024


In [63]:
# Display in the format [Day, Month DD, YYYY]
formatted_3 = current_time.strftime("%A, %B %d, %Y")
print("Format [Day, Month DD, YYYY]:", formatted_3)

Format [Day, Month DD, YYYY]: Thursday, November 07, 2024


In [64]:
# Display in the format [Day, Month DD, YYYY HH:MM:SS AM/PM]
formatted_4 = current_time.strftime("%A, %B %d, %Y %I:%M:%S %p")
print("Format [Day, Month DD, YYYY HH:MM:SS AM/PM]:", formatted_4)

Format [Day, Month DD, YYYY HH:MM:SS AM/PM]: Thursday, November 07, 2024 11:35:00 AM


In [65]:
# Format the date and time like "Thu-Jul-11 10:26:23 IST 2024"
formatted_5 = current_time.strftime("%a-%b-%d %H:%M:%S %Z %Y")
print("Format [Abbr Weekday Name-Abbr Month Name-DD HH:MM:SS IST YYYY]:", formatted_5)

Format [Abbr Weekday Name-Abbr Month Name-DD HH:MM:SS IST YYYY]: Thu-Nov-07 11:35:00  2024


In [66]:
# Display in ISO format
formatted_6 = current_time.isoformat()
print("ISO format:", formatted_6)

ISO format: 2024-11-07T11:35:00.022833


In [67]:
# Display the date only
date_only = current_time.strftime("%Y-%m-%d")
print("Date only:", date_only)

Date only: 2024-11-07


In [68]:
# Display the time only
time_only = current_time.strftime("%H:%M:%S")
print("Time only:", time_only)

Time only: 11:35:00


In [69]:
# Display the month only
month_only = current_time.strftime("%B")
print("Month only:", month_only)

Month only: November


In [70]:
# Display the year only
year_only = current_time.strftime("%Y")
print("Year only:", year_only)

Year only: 2024


# Numpy Arrays
numpy module provides a lot of numerical method functions for scientific/engineering computations. If the import step fails probably numpy is not installed. In that case skip this section.

Let's look at some of the matrix computations

In [92]:
import numpy as np
#CREATION: Let's define a 4 element vector (Similar to a list but not exactly the same)
x=np.array([1,2,3,4])
print(x)
print(x.shape)
print(type(x))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [98]:
#APPENDING
#Adding two lists concatenates them. But adding 2 numpy arrays does vector addition
print(x+x)
#We need to use the np.concatenate() function to do concatenation of numpy arrays
y=np.concatenate((x,x))
print(y)

[2 4 6 8]
[1 2 3 4 1 2 3 4]


In [102]:
#EXTRACTING/Slicing: Similar to list
#Print index 3 and 4
print(y[3:5])
#Print even indices (ie. index 0, 2, 4, 6..)
print(y[::2])
print(type(y[::2])) #Check that the slicing result is indeed a numpy array and not a list.

[4 1]
[1 3 1 3]
<class 'numpy.ndarray'>


At this level numpy looks like a second implementation of List. But the real power of numpy is its ability to handle large matrix operations really fast. Such detailed usage is outside the scope of a 1st year course. Just appreciate that numpy forms the basic building block of many scientific and machine learning applications.

# Student Exercise
To be performed independently by students.

In [ ]:
#EXERCISE: Programs to find the largest of three numbers

In [ ]:
#EXERCISE: Convert temperatures from fahrenheit to celsius. Formula c/5 = (f-32)/9

In [ ]:
#EXERCISE: Convert temperatures from celsius to fahrenheit. Formula c/5 = (f-32)/9